# Generated by Django 5.1.5 on 2025-01-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=10),
        ),
    ]
