# Generated by Django 5.1.5 on 2025-01-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SOLD', 'SOLD'), ('PURCHASE', 'PURCHASE')], max_length=10),
        ),
    ]
