# Generated by Django 5.1.5 on 2025-01-22 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0005_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
    ]
